apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-gl-saas-90yj4jgzhy39b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-gl-saas-90yj4jgzhy39b
    app.kubernetes.io/part-of: application-gl-saas-4t7p84zuna4h4
  name: component-gl-saas-90yj4jgzhy39b
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-gl-saas-90yj4jgzhy39b
status:
  loadBalancer: {}
